### ISSUE TITLE
Need method to output tables

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pbcommandR#29]
For tables and formatted text we need some way to output and display this data.

**Comment by mpkocher** [comment]
The report API has a Table model.

http://pbcommand.readthedocs.io/en/latest/report_model.html#table

**Comment by evolvedmicrobe** [comment]
Yes, the python API, but we need it in R

**Comment by mpkocher** [comment]
Can you enumerate what required to have parity with the python report API model?

**Comment by evolvedmicrobe** [comment]
Basically the direction you were already heading would be awesome. 

https://github.com/PacificBiosciences/pbcommandR/blob/master/R/pbreportsModel.R#L91

If that could take a list of data frames and produce tables in the report, we'd be all set.

**Comment by evolvedmicrobe** [comment]
Table output now enabled.
